deploy:
  # Github releases from tags
  - provider: releases
    edge: true
    draft: true
    file_glob: true
    file: "${DEPLOY_BIN}"
    on:
      tags: true
      repo: "${DEPLOY_REPO}"
      condition: $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_JOB_NAME == $DEPLOY_JOB_NAME
    edge: true
