# Setup Java on Windows amd64
_java_windows_amd64: &_java_windows_amd64
  os: windows
  language: shell
  install:
    - choco install $TRAVIS_JDK_VERSION maven
    # fix: refresh $PATH, get $M2_HOME and append it to $PATH
    - eval $(powershell -NonInteractive -Command 'write("export PATH=`"" + ([Environment]::GetEnvironmentVariable("PATH","Machine") + ";" + [Environment]::GetEnvironmentVariable("PATH","User")).replace("\","/").replace("C:","/c").replace(";",":") + ":`$PATH`"")')
    - eval $(powershell -NonInteractive -Command 'write("export M2_HOME=`"" + ([Environment]::GetEnvironmentVariable("M2_HOME","Machine")).replace("\","/").replace("C:","/c").replace(";",":") + "`"")')
    - export PATH=${M2_HOME}/bin:${PATH}
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  script:
    - mvn test -B
